name: Deploy React Frontend

on:
  push:
    branches:
      - main   # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo (required for SSH)
      - uses: actions/checkout@v3

      # 2️⃣ Pull, build, and deploy on EC2
      - name: Pull & Build on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
          
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Navigating to React app directory"
            cd /var/www/expense-tracker/expense-tracker-frontend

            echo "Resetting local changes and pulling latest code"
            git reset --hard
            git pull origin main

            echo "Installing dependencies"
            npm install

            echo "Building React app"
            npm run build

            echo "Frontend build completed. Restarting Nginx"
            sudo systemctl restart nginx

            echo "Deployment finished successfully"
